### ISSUE TITLE
some dependencies URL failure

### ISSUE THREAD

**Issue by NealRainYang** [chutsu/awesomo#17]

**Comment by NealRainYang** [comment]
The file "install_deps.bash" in [https://github.com/wavelab/atl/blob/ros/scripts/install/install_deps.bash](url) describes some dependencies for ATL project, but some apriltags project, like :

https://april.eecs.umich.edu/media/apriltag/apriltag-2016-12-01.tgz
https://svn.csail.mit.edu/apriltags

these sites are not  accessable in China，on 10 March 2019.

So, It will be very useful to put the dependencies on GitHub.

**Comment by chutsu** [comment]
Thanks for the heads up. I'm aware of this issue. Unfortunately this repo not really used anymore, so treat as more of a historical archive where it once worked.

As for the AprilTags, I have indeed hosted a copy of the AprilTags implemented by Dr. Michael Kaess here: [http://github.com/chutsu/apriltags](http://github.com/chutsu/apriltags) if you are interested. It has additional code to detect the AprilGrid used in Kalibr for calibration.
