### ISSUE TITLE
Not using ROS

### ISSUE THREAD

**Issue by wallarelvo** [chutsu/awesomo#2]
This package is not set up like a catkin package. This should be refactored.

**Comment by chutsu** [comment]
![](http://wallpapers.trestons.com/wp-content/uploads/2015/12/grumpy-cat-no-4.jpg)

**Comment by chutsu** [comment]
![grumpy-cat-no-4](https://cloud.githubusercontent.com/assets/91460/12379135/9ecf3078-bd21-11e5-92f4-2948db812651.jpg)

**Comment by chutsu** [comment]
Just kidding we'll look into it.
